### ISSUE TITLE
超级管理员默认密码是多少？

### ISSUE THREAD

**Issue by gaoyakang** [KangodYan/tealamp-admin-react#1]
超级管理员默认密码是多少？我试了123456不对啊
<img width="699" alt="截屏2024-01-08 21 18 11" src="https://github.com/KangodYan/tealamp-admin-react/assets/31574158/9027a1eb-717a-438d-9feb-c3542dcce6fb">

**Comment by kangood** [comment]
@gaoyakang 也刚好就是昨天，密码被人改了。。。我已经改回去了，你再试试

**Comment by gaoyakang** [comment]
我把项目下到本地了，部署的时候数据库里密码是0d70cc96860681487869a0304139d3410044298da40fe5b2d7acff76f83d79c8，这个明文是多少呢，我试过123456匹配不上，md5("123456")不是这个哈希值，盐值也不知道ki5pj8dv44i14yu4nbhh是啥，估计是配置里的，你给省略了，望告知，谢谢。

**Comment by kangood** [comment]
@gaoyakang 好的，首先我先给你说密码你改成 `e10adc3949ba59abbe56e057f20f883e` 就好了，对应 `123456`。

然后我把本地的数据库文件更新上去了，之前的那个是旧的没更新，你需要的话可以 pull 一下，之前的 sql 是 5.7，更新上去的是 8.0，格式有一点不一样，就看你的本地数据库版本了。

**Comment by gaoyakang** [comment]
感谢，项目已经跑起来了，我仔细研究一下。
